services:
  ml:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ml_container
    volumes:
      - .:/workspace
    # --- ADD THIS SECTION FOR GPU ACCESS ---
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # ------------------------------------
    stdin_open: true
    tty: true
