version: '3.8'

services:
  ml:
    build: 
      context: .
      dockerfile: docker/Dockerfile
    container_name: ml_container
    volumes:
      - .:/workspace
    ports:
      - "8888:8888"
    environment:
      - PYTHONPATH=/app
    stdin_open: true
    tty: true