# Project Configuration
project:
  name: "multimodal-sentiment-analysis"
  seed: 42
  device: "cuda"
  
# Data Configuration
data:
  dataset: "CMU-MOSI"
  features:
    # UPDATED to match HDF5 keys
    text: "words"
    visual: "FACET_4.2"
    audio: "COVAREP"
    labels: "Opinion Segment Labels"
  
  # Feature dimensions
  dims:
    text: 300
    visual: 35
    audio: 74
  
  # Processing
  max_seq_length: 50
  batch_size: 32
  num_workers: 2  # REDUCED to fix warnings

# Model Configuration
model:
  name: "AttentionFusion"
  hidden_dim: 128  # REDUCED for stability
  num_heads: 4     # REDUCED for stability
  dropout: 0.3     # INCREASED for regularization
  fusion_dim: 256  # REDUCED for stability
  num_classes: 3

# Training Configuration
training:
  epochs: 100
  learning_rate: 0.0001  # REDUCED for stability
  weight_decay: 0.01     # INCREASED for regularization
  gradient_clip: 0.5     # REDUCED for stability
  scheduler: "cosine"
  early_stopping_patience: 10
  
# Logging Configuration
logging:
  log_interval: 10
  save_interval: 5
  tensorboard: true
  wandb: false
  
# Paths - UPDATED TO BE RELATIVE
paths:
  data_dir: "data"
  output_dir: "outputs"
  model_dir: "outputs/models"
  log_dir: "outputs/logs"