# Project Configuration
project:
  name: "multimodal-sentiment-analysis"
  seed: 42
  device: "cuda"
  
# Data Configuration
data:
  dataset: "CMU-MOSI"
  features:
    # UPDATED to match HDF5 keys
    text: "words"
    visual: "FACET_4.2"
    audio: "COVAREP"
    labels: "Opinion Segment Labels"
  
  # Feature dimensions
  dims:
    text: 300
    visual: 35
    audio: 74
  
  # Processing
  max_seq_length: 50
  batch_size: 32
  num_workers: 4
  
  # Splits (video IDs) - Note: These are not used with the HDF5 data
  train_split: ['2iD-tVS8NPw', '8d-gEyoeBzc', 'Qg1p4z1hpvo']
  valid_split: ['HEsqSxL_c2s', 'OtVxDvYrj8Y']
  test_split: ['BC9XOoKn5DI', 'h3UEqsqG-ec']

# Model Configuration
model:
  name: "AttentionFusion"
  hidden_dim: 256
  num_heads: 8
  dropout: 0.2
  fusion_dim: 512
  num_classes: 3

# Training Configuration
training:
  epochs: 100
  learning_rate: 0.001
  weight_decay: 0.0001
  gradient_clip: 1.0
  scheduler: "cosine"
  early_stopping_patience: 10
  
# Logging Configuration
logging:
  log_interval: 10
  save_interval: 5
  tensorboard: true
  wandb: false
  
# Paths - UPDATED TO BE RELATIVE
paths:
  data_dir: "data"
  output_dir: "outputs"
  model_dir: "outputs/models"
  log_dir: "outputs/logs"